"""empty message

Revision ID: 435a17cf98b3
Revises: e3e01ed37a0c
Create Date: 2016-05-12 01:08:49.474097

"""

# revision identifiers, used by Alembic.
revision = '435a17cf98b3'
down_revision = 'e3e01ed37a0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('minimum_pledge_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pledge') as batch_op:
        batch_op.add_column(sa.Column('reward_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('pledge', 'reward', ['reward_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pledge') as batch_op:
        batch_op.drop_constraint('pledge', type_='foreignkey')
        batch_op.drop_column('reward_id')
    op.drop_table('reward')
    ### end Alembic commands ###
