"""empty message

Revision ID: 61f132d627da
Revises: 9b930f498099
Create Date: 2016-05-08 19:12:11.381184

"""

# revision identifiers, used by Alembic.
revision = '61f132d627da'
down_revision = '9b930f498099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
