"""empty message

Revision ID: 7efcdcc05b3e
Revises: 435a17cf98b3
Create Date: 2016-05-14 00:27:26.885247

"""

# revision identifiers, used by Alembic.
revision = '7efcdcc05b3e'
down_revision = '435a17cf98b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    category_table = ('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project') as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('project', 'category', 'category_id', 'id')
        
        op.bulk_insert(category_table,
    [
        {'id':1, 'name':'Art', 'slug':'art'},
        {'id':2, 'name':'Comics', 'slug':'comics'},
        {'id':3, 'name':'Crafts', 'slug':'crafts'},
        {'id':4, 'name':'Dance', 'slug':'dance'},
        {'id':5, 'name':'Design', 'slug':'design'},
        {'id':6, 'name':'Fashion', 'slug':'fashion'},
        {'id':7, 'name':'Film & Video', 'slug':'film-video'},
        {'id':8, 'name':'Food', 'slug':'food'},
        {'id':9, 'name':'Games', 'slug':'games'},
        {'id':10, 'name':'Journalism', 'slug':'journalism'},
        {'id':11, 'name':'Music', 'slug':'music'},
        {'id':12, 'name':'Photography', 'slug':'photography'},
        {'id':13, 'name':'Publishing', 'slug':'publishing'},
        {'id':14, 'name':'Technology', 'slug':'technology'},
        {'id':15, 'name':'Theater', 'slug':'theater'},
        {'id':16, 'name':'Other', 'slug':'other'}
    ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project') as batch_op:
        batch_op.drop_constraint('project', type_='foreignkey')
        batch_op.drop_column('category_id')
    op.drop_table('category')
    ### end Alembic commands ###
